### ISSUE TITLE
You didn't add us to the credits.

### ISSUE THREAD

**Issue by MemeHoovy** [Joalor64GH/Joalor64-Engine#21]
### What is your issue?

To clarify, the AssetManager thing was made by Yoshubs, albeit with some additions by me, and it's not finished yet.
I'm not a very good coder, compared to shubs (I can't stop comparing myself to others). But I would still appreciate it if you added us to the credits, thanks. (I know this isn't an actual issue, but still.)

**Comment by Joalor64GH** [comment]
DW, I'll take care of it.

**Comment by MemeHoovy** [comment]
> DW, I'll take care of it.

ok, thanks
