### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [Joalor64GH/Joalor64-Engine#22]
### What is your question?

I know your very busy- but i made an engine and i was wondering if there is any tips?

**Comment by LEVIXDDLMAO** [comment]
Here the engine :D https://github.com/LEVIXDDLMAO/FNF-SwagEngine

**Comment by Joalor64GH** [comment]
Good question. One thing I would do is try adding unique features.
Like, features that some people haven't thought of before.
And maybe add your own original ideas.

**Comment by LEVIXDDLMAO** [comment]
oo! Okay! Thank you! this is my second time making an engine my old engine did get update witch was call funked Engine
