### ISSUE TITLE
Buttons in debug don't appear.

### ISSUE THREAD

**Issue by TheKamboy** [Joalor64GH/Joalor64-Engine#25]
### Describe your bug here.

When you open debug mode, most of the buttons don't appear.

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by ShadowMilky** [comment]
over a month, and this still hasn’t been fixed

**Comment by Joalor64GH** [comment]
i forgot about this issue but it's been fixed lol
