### ISSUE TITLE
I found the bug

### ISSUE THREAD

**Issue by BambiGaming2022** [Joalor64GH/Joalor64-Engine#30]
### Describe your bug here.

[https://cdn.discordapp.com/attachments/1060615218222350339/1060615244264775710/image.png](url)

### Command Prompt/Terminal logs (if existing)

```bash
nothing
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by BambiGaming2022** [comment]
there is no buttons in chart editor

**Comment by Joalor64GH** [comment]
i'll figure out how to fix it

**Comment by BambiGaming2022** [comment]
thx

**Comment by Joalor64GH** [comment]
i update the repo so that it's compatible with flixel 5.3
if that still doesn't fix it, idk
but yeah

**Comment by BambiGaming2022** [comment]
Well, My haxe and flixel is broken

**Comment by Joalor64GH** [comment]
good news
i finally fixed it

**Comment by BambiGaming2022** [comment]
Finally
