### ISSUE TITLE
the zip bug

### ISSUE THREAD

**Issue by OliwerGamer64** [Joalor64GH/Joalor64-Engine#6]
### Describe your bug here.

if i unzip it won't work pls help me or fix this

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

idk what do say lol

**Comment by OliwerGamer64** [comment]
> Did you just download the engine itself, or compile the source code?

yes but it won't work help me

**Comment by OliwerGamer64** [comment]
> What happens when you try to open it?

it won't let me unzip your source code pls fix this

**Comment by Joalor64GH** [comment]
Do you have WinRAR? If not, I suggest downloading it. Then, maybe the problem will be fixed.

**Comment by OliwerGamer64** [comment]
> Do you have WinRAR? If not, I suggest downloading it. Then, maybe the problem will be fixed.

yes i do have winrar but it won't let me unzip your source code, idk is your source code file is corrupted or what

**Comment by Joalor64GH** [comment]
Do you have enough space in your device?

**Comment by OliwerGamer64** [comment]
> Do you have enough space in your device?

i have 75gb space i didn't get full it's fine but then HOW DO I UNZIP YOUR SOURCE CODE FILE

**Comment by Joalor64GH** [comment]
Try to right-click on the zip, and find the option that says, "Extract Files".

**Comment by Joalor64GH** [comment]
What device are you on?

**Comment by Joalor64GH** [comment]
Maybe, the zip wasn't downloaded properly??
Or maybe you should try WinZip.

**Comment by OliwerGamer64** [comment]
> Maybe, the zip wasn't downloaded properly?? Or maybe you should try WinZip.

didn't work it says one or file

**Comment by Joalor64GH** [comment]
Try looking though this:
https://support.cloudhq.net/cant-unzip-folder-is-invalid-or-similar-windows/

**Comment by OliwerGamer64** [comment]
> Try looking through this: https://support.cloudhq.net/cant-unzip-folder-is-invalid-or-similar-windows/

this website won't help me and pls fix this

**Comment by OliwerGamer64** [comment]
> Try looking through this: https://support.cloudhq.net/cant-unzip-folder-is-invalid-or-similar-windows/

i tried to unzip into a 7zip and data error into a winter horrorland inst

**Comment by OliwerGamer64** [comment]
> Try looking through this: https://support.cloudhq.net/cant-unzip-folder-is-invalid-or-similar-windows/

now i coped and paste winter horrorland inst and voices and paste into that and now it fixed
(10,000 IQ)

**Comment by Joalor64GH** [comment]
Oh thank goodness.
