### ISSUE TITLE
2 Bugs Issues + Shader Issue

### ISSUE THREAD

**Issue by OliwerGamer64** [Joalor64GH/Joalor64-Engine#8]
### Describe your bug here.

1. if the rank is on screen i can't go to the next song on story mode it's just there i sit like 2 mins and nothing happened
2. if i put animated icons it won't work
3. also shaders are hidden and i can't found them to turn on shaders pls add them (this can be seen in the files)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

idk what do say lol

**Comment by Joalor64GH** [comment]
1. When the results screen comes up, press space to continue.
2. You need a Lua Script for animated icons.
3. The shaders are in assets/preload/shaders. Also idk how they work so yeah.

**Comment by OliwerGamer64** [comment]
> 1. When the results screen comes up, press space to continue.
> 2. You need a Lua Script for animated icons.
> 3. The shaders are in assets/preload/shaders. Also all of those are just examples.

i don't see preload folder

**Comment by Joalor64GH** [comment]
Oh wait. Then they're in assets/shaders.

**Comment by OliwerGamer64** [comment]
> Oh wait. Then they're in assets/shaders.

and then how do i turn on shaders in the game

**Comment by Joalor64GH** [comment]
This should help:
https://www.youtube.com/watch?v=kCYI84vsrQM

**Comment by OliwerGamer64** [comment]
> This should help: https://www.youtube.com/watch?v=kCYI84vsrQM

coding is too hard for me
hold on let me do without coding

**Comment by OliwerGamer64** [comment]
> This should help: https://www.youtube.com/watch?v=kCYI84vsrQM

sorry won't work i guess shaders is only for coding

**Comment by Joalor64GH** [comment]
oh
